name: GitHub Actions Demo
# 触发条件 (master分支的push操作)
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # 登录阿里云私有镜像仓库,用于后面的push镜像
      - name: Login to Aliyun image registry
        uses: docker/login-action@v2
        # 此处需要填写镜像仓库的相关配置，为了保护隐私，需在仓库设置中创建secret
        with:
          registry: ${{ secrets.ALIYUN_IMAGE_REGISTRY_ADDRESS }}
          username: ${{ secrets.ALIYUN_IMAGE_REGISTRY_PASSWORD }}
          password: ${{ secrets.ALIYUN_IMAGE_REGISTRY_USERNAME }}
      - uses: actions/checkout@v3
      # 设置java环境
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      # 执行打包操作
      - run: mvn --batch-mode --update-snapshots package
      # 设置镜像原信息,包括镜像名和版本号
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        # 这里的参数可以参考 https://github.com/docker/metadata-action
        with:
          # 镜像名一般固定写死
          images: registry.cn-hangzhou.aliyuncs.com/lksun-test/github-action-demo
          # metadata-action 为我们提供了多种标签命名规则 (⚠ 下面的时间非北京时间)
          tags: |
            type=raw,value={{branch}}-{{date 'YYYYMMDDhhmmss'}}
      # 推送镜像
      - uses: docker/build-push-action@v3
        # 这里的参数可以参考 https://github.com/docker/build-push-action#customizing
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
