name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  # 根据dockerfile构建镜像并发布到镜像仓库
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Aliyun image registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_IMAGE_REGISTRY_ADDRESS }}
          username: ${{ secrets.ALIYUN_IMAGE_REGISTRY_PASSWORD }}
          password: ${{ secrets.ALIYUN_IMAGE_REGISTRY_USERNAME }}
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots package
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: registry.cn-hangzhou.aliyuncs.com/lksun-test/github-action-demo
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
