name: GitHub Actions Demo
# 触发条件 (master分支的push操作)
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # 登录阿里云私有镜像仓库,用于后面的push镜像
      - name: Login to Aliyun image registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_IMAGE_REGISTRY_ADDRESS }}
          username: ${{ secrets.ALIYUN_IMAGE_REGISTRY_PASSWORD }}
          password: ${{ secrets.ALIYUN_IMAGE_REGISTRY_USERNAME }}
      - uses: actions/checkout@v3
      # 设置java环境
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      # 执行打包操作
      - run: mvn --batch-mode --update-snapshots package
      # 设置镜像原信息
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: registry.cn-hangzhou.aliyuncs.com/lksun-test/github-action-demo
      # 推送镜像
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
