name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  # 登录阿里云容器仓库
  login-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Aliyun image registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_IMAGE_REGISTRY_ADDRESS }}
          username: ${{ secrets.ALIYUN_IMAGE_REGISTRY_PASSWORD }}
          password: ${{ secrets.ALIYUN_IMAGE_REGISTRY_USERNAME }}
  # 根据dockerfile构建镜像并发布到镜像仓库
  publish-image:
    #needs: [login-registry,package]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        run: |
          cat ./Dockerfile