name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  # 步骤一 自动执行单元测试
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
  # 步骤二 构建jar包
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots package
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Aliyun image registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_IMAGE_REGISTRY_ADDRESS }}
          username: ${{ secrets.ALIYUN_IMAGE_REGISTRY_PASSWORD }}
          password: ${{ secrets.ALIYUN_IMAGE_REGISTRY_USERNAME }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: registry.cn-hangzhou.aliyuncs.com/lksun-test/github-action-demo
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}